---
# tasks file for ansible-role-virtualbox

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ virtualbox_log_dir }}"
    mode: 0755
    owner: "{{ virtualbox_user }}"
    group: "{{ virtualbox_group }}"
    state: directory
  notify: Restart virtualbox

- name: Create db directory
  file:
    path: "{{ virtualbox_db_dir }}"
    mode: 0755
    owner: "{{ virtualbox_user }}"
    group: "{{ virtualbox_group }}"
    state: directory
  notify: Restart virtualbox

- name: Create virtualbox.conf
  template:
    src: virtualbox.conf.j2
    dest: "{{ virtualbox_conf_file }}"
    validate: echo %s
  notify: Restart virtualbox

- name: Start virtualbox
  service:
    name: "{{ virtualbox_service }}"
    enabled: true
    state: started
